// Column order of the two sheets in "Wheat Punjab - Regen AG5.1 Annual Crop Import Data.xlsx".
// Copied verbatim (including typos and trailing spaces) so exported CSVs import cleanly.

export const REGEN_COLUMNS = [
  "DisplayID",
  "Name",
  "ExternalID",
  "General Infomation - Entity UID",
  "General Infomation - FAT Dairy V5_UID",
  "General Infomation - Data Version",
  "General Infomation - Metadata Version",
  "General Infomation - Date Of The Data Collection",
  "General Infomation - Year of reporting",
  "Farmer Name",
  "Kisaan Advisor Name",
  "General Infomation - Date of the data creation",
  "General Infomation - Is there any evidence to submit?",
  "General Infomation - Evidence Photo",
  "Farm - Arable crop land (ha)",
  "Farm - Permanent crop land (ha), e.g. fruit orchards, coffee, cocoa, etc.",
  "Farm - Permanent pastures (ha)",
  "Farm - Natural habitat and natural forest area (ha)",
  "Farm - Agricultural Area (All Land) (ha)",
  "Farm - Number of livestock (Standard Livestock Units)",
  "Farm - Reference field for soil organic matter (please consider representative field of whole farm)",
  "Farm - Percentage of Soil Organic Matter in referenced field",
  "Farm - Source of the data",
  "Farm - Year of soil analysis assessment",
  "Farm - Certificates/Label Production",
  "Farm - Name of Certificate / Label",
  "Farm - Crop ",
  "Farm - Total produced volume of the year -1 (kg/year) on the farm",
  "Soil - 1.01 On average, how many different types of crops do you grow on the same piece of land over a period of 3 years? Cover crops, even multispecies are considered as one crop, whereas intercrops are considered as additional crops",
  "Soil - 1.02 What is the percentage of arable crop land subjected to rotations with at least X different types of crops including cover crops and/or intercrops (X=No. Of crops in Q1.01)? (land with X different types of crops in rotation/total crop land)",
  "Soil - 1.03 What is the percentage of arable crop land planted with cover crops? (land with cover crop/total crop land x 100)",
  "Soil - 1.04 How many of these 5 cover crop types you included in the mixture like grasses, legumes, brassicas non-legume broadleaves, deep root",
  "Soil - 1.05 What is the percentage of crop land with application of crop residues, mulch, grass clipping, straw, etc.? (land with application /total crop land x 100)",
  "Soil - 1.06 What is the percentage of arable crop land covered by at least 10 months, with crops, cover crops, grasses, plant residues or mulch?",
  "Soil - 1.07 What is the percentage of arable crop land managed with minimum tillage? (land with minimal till/total crop land x 100)",
  "Soil - 1.08 Do you calculate your fertilizer plan (nutrient balance) on the basis of the 4 R Nutrient Stewardship Principles. If partially yes, how many of the following principles do you apply:  (a) Right Source,  (b) Right Rate, (c) Right Time, (d) Right Place)?",
  "Soil - 1.09 Percentage of synthetic N used vs total N",
  "Soil - 1.10 Nitrogen fertilizer productivity",
  "Soil - 1.11 Do you burn crop residue in more than 10% of your field?",
  "Soil - 1.12 On average, what is the interval of soil analysis for texture, pH, soil organic matter, phosphorus, potassium (excluding nitrogen)?",
  "Soil - FAT V4 Fertilizer Productivity 113 ",
  "Soil - 1.14 Has the SOM increased since the last soil analysis?",
  "Biodiversity and Land use - 2.01 Do you follow Integrated Pest Management (IPM) principles when applying plant protection products? If partially yes, how many of the following principles do you apply: (a) Appropriate pest and disease monitoring, (b) Appropriate intervention measures, (c) Appropriate quantity/dose, (d) Appropriate time, (e) Appropriate place",
  "Biodiversity and Land use - 2.02 What is the percentage of crop land without synthetic pest and disease control (land without synthetic pest control/ total crop land x 100)",
  "Biodiversity and Land use - 2.03 What is the percentage of crop and pasture land without synthetic herbicide application? (land without synthetic herbicide control/ total crop land x 100)",
  "Biodiversity and Land use - 2.04 What is the percentage of agricultural area being biodiversity habitats such as hedge, trees alley, flower strip, natural habitats, green belts, riparian area, non farmed area (that could potentially be cultivated) etc? (agriculture area with biodiversity habitat / total crop land x 100)",
  "Biodiversity and Land use - 2.05 What is the percentage of agriculture area dedicated to agroforestry (productive areas in a field with combinations of crops or pasture with multiple types of productive bushes & trees)? (agriculture area with agroforestery/total agriculture area x 100)",
  "Biodiversity and Land use - 2.06 Do you have a recorded and tracked Biodiversity action plan in place at farm scale?",
  "Water - 3.01a If you have to irrigate, select the predominant irrigation system used on irrigated crop",
  "Water - 3.02 Do you monitor the water consumption at crop level and is data recording available?",
  "Water - 3.03 Do you control irrigation with digital soil moisture sensors?",
  "Water - 3.04 If you have water bodies at your farm (eg. rivers, ponds, lakes), what is the minimum distance between field application area (fertilizer/manure and pesticide) and the water body?",
  "Water - 3.05 What is the percentage of water bodies with riparian buffer strips such as bushes, trees, etc.?  (Length of adjacent water body with riparian buffer/ total length of adjacent water body x 100)",
  "Water - 3.06 What % of your water bodies fenced from animal access? (Length of water body fenced / total length of water body x 100)",
  "Livestock - 4.01 What is the proportion of protein feed traceable to low risk, non-deforested areas (since year: 2010)? (protein from low risk area /total protein requirement x 100)",
  "Livestock - 4.02 What is the proportion of feed and fodder grown on farm? (DM feed grown on farm/total DM feed used x 100)",
  "Livestock - 4.03 What is the percentage of multispecies pastures/grasslands with at least three species including grasses, legumes and broad leaves? (pastures with multispecies/total pasture x 100)",
  "Livestock - 4.04 What is the percentage of pasture area under mob grazing and rotational grazing management? (pasture area under mob grazing and rotational grazing/total pasture area x 100)",
  "Livestock - 4.05 What is the percentage of pastures/grasslands established on minimum tillage or direct seeding practices? (to pastures/grasslands with minimum till or direct seeding/total pastures grasslands x 100)",
  "Livestock - 4.06 What is the average productivity level in the herd? (kg milk/day)",
  "Livestock - 4.07 Do you track the use of antibiotics and hormones; if yes, how do you use these? (Prevention or treatment)",
  "Livestock - 4.08 How do you store your liquid and solid manure?",
  "Livestock - 4.09 How do you fertilize your fields?",
  "Livestock - 4.10 How do you handle and treat farm generated waste water?",
  "Competencies - 5.01 Have you understood the main principles of Regenerative Agriculture? (for example attending training session or reading the 4 pages of RegenAgr in Nestle)",
  "Competencies - 5.02 Do you keep agricultural management records (i.e. spray records, fertilizer records, etc.)?",
  "Competencies - 5.03 Do you make use of precision farming technologies such as (a) automated parallel driving systems in machines, (b) section control or variable rate application of fertilizers or pesticides, (c) the use of digital farm and/or animal decision support tools and (d) optical sensors? If yes, how many types of technologies do yo make use of?",
  "Approval Status - Approval Status",
  "Approval Status - Remarks Approval Questionnaire",
  "Approval Status - Path File Approval Questionnaire",
  "Approval Status - Complete Status",
  "Approval Status - Crop Footprint",
  "Rules - Conventional Farmer - FAT Dairy"
]

export const CROP_COLUMNS = [
  "DisplayID",
  "Name",
  "ExternalID",
  "Crop - Entity UID",
  "Crop - FAT Dairy V5_UID",
  "Crop - FAT Dairy V5 Crop_UID",
  "Crop - Crop",
  "Crop - Area (ha)",
  "Crop - Yield (t/ha)",
  "Crop - Dry Matter Content (%)",
  "Crop - Synthetic + Organic Nitrogen applied (kg/ha)",
  "Crop - Synthetic Nitrogen applied (kg/ha)",
  "Crop - Water applied through irrigation (m3/ha)",
  "Crop - Number of  applications of synthetic pesticide"
]
